name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Prepare Plugin
        run: |
          cd ${{ github.workspace }}
          git submodule update --init --recursive
          mkdir -p ./onlyofficeeditor
          rsync -av --exclude='onlyofficeeditor' ./ ./onlyofficeeditor
          cd ./onlyofficeeditor
          rm -rf ./.github/
          rm -rf ./.git/
      - name: Checkout Moodle
        uses: actions/checkout@v3
        with:
          repository: moodle/moodle
          path: ./moodle
      - name: Copy Plugin
        run: |
          cp -r onlyofficeeditor ./moodle/mod/onlyofficeeditor
      - name: Build Plugin
        run: |
          cd ./moodle
          npm install
          grunt
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          mv ./moodle/mod/onlyofficeeditor ./moodle/mod/moodle-mod_onlyofficeeditor-${{ steps.info.outputs.version }}
          mkdir -p ./deploy
          cp -r ./moodle/mod/moodle-mod_onlyofficeeditor-${{ steps.info.outputs.version }} ./deploy
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: moodle-mod_onlyofficeeditor-v${{ steps.info.outputs.version }}
          path: deploy